name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"  

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
          pip install playwright  

      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium
          python -m playwright install-deps

      - name: Build release distributions
        run: |
          python -m build --wheel
          python -m build --sdist

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Verify distributions
        run: |
          pip install twine
          twine check dist/*

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true
          skip-existing: true